export const ACCOUNT_PRIVACY_OPTIONS = [
    { label: "Public", value: "public" },
    { label: "Followers Only", value: "followers_only" },
    { label: "Private", value: "private" },
] as const;

export const FOLLOW_REQUESTS_OPTIONS = [
    { label: "Direct Follow", value: "direct_follow" },
    { label: "Requires Approval", value: "requires_approval" },
] as const;

export const COUNTRY_OPTIONS = [
    { label: "United States", value: "US" },
    { label: "United Kingdom", value: "GB" },
    { label: "Germany", value: "DE" },
    { label: "France", value: "FR" },
    { label: "Egypt", value: "EG" },
    { label: "Japan", value: "JP" },
    { label: "Australia", value: "AU" },
    { label: "Syria", value: "SY" },
    { label: "United Arab Emirates", value: "AE" },
    { label: "Saudi Arabia", value: "SA" },
    { label: "Algeria", value: "DZ" },
    { label: "Argentina", value: "AR" },
    { label: "Austria", value: "AT" },
    { label: "Bahrain", value: "BH" },
    { label: "Belgium", value: "BE" },
    { label: "Brazil", value: "BR" },
    { label: "Canada", value: "CA" },
    { label: "China", value: "CN" },
    { label: "Denmark", value: "DK" },
    { label: "Finland", value: "FI" },
    { label: "Greece", value: "GR" },
    { label: "India", value: "IN" },
    { label: "Indonesia", value: "ID" },
    { label: "Iraq", value: "IQ" },
    { label: "Ireland", value: "IE" },
    { label: "Italy", value: "IT" },
    { label: "Jordan", value: "JO" },
    { label: "Kuwait", value: "KW" },
    { label: "Lebanon", value: "LB" },
    { label: "Malaysia", value: "MY" },
    { label: "Mexico", value: "MX" },
    { label: "Morocco", value: "MA" },
    { label: "Netherlands", value: "NL" },
    { label: "New Zealand", value: "NZ" },
    { label: "Norway", value: "NO" },
    { label: "Oman", value: "OM" },
    { label: "Pakistan", value: "PK" },
    { label: "Palestine", value: "PS" },
    { label: "Poland", value: "PL" },
    { label: "Portugal", value: "PT" },
    { label: "Qatar", value: "QA" },
    { label: "South Korea", value: "KR" },
    { label: "Spain", value: "ES" },
    { label: "Sweden", value: "SE" },
    { label: "Switzerland", value: "CH" },
    { label: "Tunisia", value: "TN" },
    { label: "Turkey", value: "TR" },
] as const;

export const THEME_OPTIONS = [
    { label: "Dark", value: "dark" },
    { label: "Light", value: "light" },
    { label: "System", value: "system" },
] as const;